# Generated by Django 4.1 on 2022-09-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_fruit_price_per_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
