# Generated by Django 4.1 on 2022-09-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_category_fruit'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
