# Generated by Django 4.1 on 2022-09-09 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_fruit_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
