# Generated by Django 4.1 on 2022-09-09 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_fruit_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruit',
            name='title',
        ),
    ]
