# Generated by Django 4.1 on 2022-09-10 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_fruit_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='fruit',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='fruit',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.category'),
        ),
    ]
